### ISSUE TITLE
How can the tablet miss the MAC address?

### ISSUE THREAD

**Issue by TRECRF** [ljlVink/msyk-fakeserver-generator#1]
Flash the factory system?

**Comment by ljlVink** [comment]
不用，1.在平板wifi的那里能看见硬件mac地址
           2.平板连接路由器，也有mac地址
           3.触发linspirer的bug清除数据在输入正确的密码后会出license里面有mac地址

**Comment by ljlVink** [comment]
哦，你说的是这个呀，mac地址刷机是不会变的，因为它是硬件固化的

**Comment by ljlVink** [comment]
这个除了有地址验证外，还有系统版本验证，

**Comment by TRECRF** [comment]
I saw“破解后不能登录的平板” and wrote that.

**Comment by TRECRF** [comment]
> 哦，你说的是这个呀，mac地址刷机是不会变的，因为它是硬件固化的

In fact,,emui devices' mac don't write in the hardware.It's written in the UFS/EMMC.Even it can be changed(Not using xposed to cheat software)

**Comment by TRECRF** [comment]
> 2.平板连接路由器，也有mac地址

If you own the BZA-W00,MAC is also written in the SD Card Holder.

**Comment by ljlVink** [comment]
我们学校不是华为的平板，是联想的，我曾在刷机前知道了mac地址，后来刷机后对比没有发生改变，不知道华为的设备表现

Our school is not Huawei's tablet, it's Lenovo's. I once knew the MAC address before I swiped the computer, but the comparison didn't change after I swiped the computer. I don't know Huawei's equipment performance

**Comment by TRECRF** [comment]
算了 直接说吧/doge
mac并没有固化到soc 据我所知，写字库和很多厂商安卓设备都这么干，联想可能是9008刷的时候，那个xml刷机脚本没wipe存储串号的分区，导致刷了也不丢串

**Comment by ljlVink** [comment]
你是哪个地区的呀，我们这就两三所学校用，好像就有一家抢到华为平板了

**Comment by TRECRF** [comment]
> 你是哪个地区的呀，我们这就两三所学校用，好像就有一家抢到华为平板了

我把我qq挂到资料上 私下说吧

**Comment by TRECRF** [comment]
> 你是哪个地区的呀，我们这就两三所学校用，好像就有一家抢到华为平板了



> 你是哪个地区的呀，我们这就两三所学校用，好像就有一家抢到华为平板了

万朋官网不是吹华为高端平板呢 怎么还混用联想了 
领创倒是好几个厂商都适配了 我们省我知道的全是华为

**Comment by TRECRF** [comment]
> 我们学校不是华为的平板，是联想的，我曾在刷机前知道了mac地址，后来刷机后对比没有发生改变，不知道华为的设备表现

还是刷机过程中是否擦除存储串号的分区 擦了就完 但部分华为还能写回来抢救

**Comment by ljlVink** [comment]
加我Q:1666217358

**Comment by TRECRF** [comment]
> 加我Q:1666217358

ok 删了吧
